import 'package:intl_phone_field/countries.dart';

const allowedCountries = [
  Country(
    name: "United States",
    nameTranslations: {
      "sk": "Spojené štáty",
      "se": "Amerihká ovttastuvvan stáhtat",
      "pl": "Stany Zjednoczone",
      "no": "USA",
      "ja": "アメリカ合衆国",
      "it": "Stati Uniti",
      "zh": "美国",
      "nl": "Verenigde Staten",
      "de": "Vereinigte Staaten",
      "fr": "États-Unis",
      "es": "Estados Unidos",
      "en": "United States",
      "pt_BR": "Estados Unidos",
      "sr-Cyrl": "Сједињене Америчке Државе",
      "sr-Latn": "Sjedinjene Američke Države",
      "zh_TW": "美國",
      "tr": "Amerika Birleşik Devletleri",
      "ro": "Statele Unite ale Americii",
      "ar": "الولايات المتحدة",
      "fa": "ایالات متحده آمریکا",
      "yue": "美利堅郃眾囯"
    },
    flag: "🇺🇸",
    code: "US",
    dialCode: "1",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "France",
    nameTranslations: {
      "sk": "Francúzsko",
      "se": "Frankriika",
      "pl": "Francja",
      "no": "Frankrike",
      "ja": "フランス",
      "it": "Francia",
      "zh": "法国",
      "nl": "Frankrijk",
      "de": "Frankreich",
      "fr": "France",
      "es": "Francia",
      "en": "France",
      "pt_BR": "França",
      "sr-Cyrl": "Француска",
      "sr-Latn": "Francuska",
      "zh_TW": "法國",
      "tr": "Fransa",
      "ro": "Franța",
      "ar": "فرنسا",
      "fa": "فرانسه",
      "yue": "法國"
    },
    flag: "🇫🇷",
    code: "FR",
    dialCode: "33",
    minLength: 9,
    maxLength: 10,
  ),
  Country(
    name: "Switzerland",
    nameTranslations: {
      "sk": "Švajčiarsko",
      "se": "Šveica",
      "pl": "Szwajcaria",
      "no": "Sveits",
      "ja": "スイス",
      "it": "Svizzera",
      "zh": "瑞士",
      "nl": "Zwitserland",
      "de": "Schweiz",
      "fr": "Suisse",
      "es": "Suiza",
      "en": "Switzerland",
      "pt_BR": "Suíça",
      "sr-Cyrl": "Швајцарска",
      "sr-Latn": "Švajcarska",
      "zh_TW": "瑞士",
      "tr": "İsviçre",
      "ro": "Elveţia",
      "ar": "سويسرا",
      "fa": "سوئیس",
      "yue": "瑞士"
    },
    flag: "🇨🇭",
    code: "CH",
    dialCode: "41",
    minLength: 9,
    maxLength: 12,
  ),
  Country(
    name: "Luxembourg",
    nameTranslations: {
      "sk": "Luxembursko",
      "se": "Luxembourg",
      "pl": "Luksemburg",
      "no": "Luxemburg",
      "ja": "ルクセンブルク",
      "it": "Lussemburgo",
      "zh": "卢森堡",
      "nl": "Luxemburg",
      "de": "Luxemburg",
      "fr": "Luxembourg",
      "es": "Luxemburgo",
      "en": "Luxembourg",
      "pt_BR": "Luxemburgo",
      "sr-Cyrl": "Луксенбург",
      "sr-Latn": "Luksenburg",
      "zh_TW": "盧森堡",
      "tr": "Lüksemburg",
      "ro": "Luxemburg",
      "ar": "لوكسمبورغ",
      "fa": "لوکزامبورگ",
      "yue": "盧森堡"
    },
    flag: "🇱🇺",
    code: "LU",
    dialCode: "352",
    minLength: 11,
    maxLength: 11,
  ),
];
