name: date_me
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http:
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  connectivity_plus: ^4.0.2
  intl: ^0.18.0
  flutter_svg: ^2.0.5
  sizer: ^2.0.15
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  salomon_bottom_bar: ^3.3.2
  like_button: ^2.0.5
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  fan_carousel_image_slider: ^0.1.2
  animated_toggle_switch: ^0.7.0
  transitioned_indexed_stack: ^1.0.2
  appinio_swiper: ^2.1.1
  expandable_text: 2.3.0
  flutter_spinkit: ^5.0.0
  intl_phone_field: ^3.2.0
  pinput: ^2.2.31
  adaptive_theme: ^3.4.0
  image_picker: ^1.0.4
  image_cropper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/icons/


  fonts:
    - family: Rubik
      fonts:
        - asset: lib/assets/fonts/Rubik-Regular.ttf
        - asset: lib/assets/fonts/Rubik-Bold.ttf
        - asset: lib/assets/fonts/Rubik-Medium.ttf

